### ISSUE TITLE
sos where is the libcaffe.a

### ISSUE THREAD

**Issue by joyousrabbit** [jetsonhacks/installCaffeJTX2#3]
Hello, I tryed again and again. However the TX2 only generate libcaffe.so, no libcaffe.a.

It's very strange because in my PC the caffe does generate both .so and .a.

What happened to TX2 and how can we get a libcaffe.a please.

This is very urgent for my project please help.

**Comment by jetsonhacks** [comment]
How did you modify the script to attempt to build the static library?

**Comment by joyousrabbit** [comment]
Thank you for reply. I modified it by 2 ways.
1) I read your installCaffe script and found that it use the same source of caffe from git as my PC (by git clone https://github.com/BVLC/caffe.git) . 

So I think that the only difference from compiling from PC is that, in your script there is " cmake -DCUDA_USE_STATIC_CUDA_RUNTIME=OFF " before make all in TX2. Then I modified it to "ON" by "" cmake -DCUDA_USE_STATIC_CUDA_RUNTIME=ON ".

However, this modification doesn't generate libcaffe.a

2) I grep all files to find key word "libcaffe.so" and "libprotobuf.a" that are generated successully. I did found them in CaffeTargets.cmake. So I modified the libcaffe.so target to libcaffe.a.  Failed to generate libcaffe.a again.

Why with the same source code from github, my PC can generate libcaffe.a but the TX2 cannot? Is it a problem of configuration?

Please help.

**Comment by jetsonhacks** [comment]
Did you use the same cmake configuration that you used for your PC? I am under the impression that the flag for static compilation is BUILD_SHARED_LIBS=OFF
You don't mention how you are building this for the PC.

**Comment by joyousrabbit** [comment]
On my PC it's by default.
cp Makeconfig.example.save Makeconfig.example
make all -j8
Then it generates both libcaffe.a and libcaffe.so. No special configuration.

**Comment by joyousrabbit** [comment]
And I just verified that on my PC, the cmake was even not installed. 
Caffe contains the makefile which is directly called by make  instead of cmake.

**Comment by jetsonhacks** [comment]
The CMake version does not build both the dynamic and static libraries by default, it builds one or the other. 
You can use make instead if so desired. I do recall that using a static CUDA runtime on the TX2 causes issues, I am not sure if this has been fixed in later releases.

**Comment by joyousrabbit** [comment]
Thank you the problem is revolved! I removed wholely the caffe folder, rerun your installCaffe.sh script without the CMake line, everything is OK. 

I didn't realize the CMake changed the BUILD_STATIC_LIBARYR configue in Makefile. How can you know such a detail? You are a hero!

**Comment by jetsonhacks** [comment]
I'm glad you got it to work.
