### ISSUE TITLE
error while running installcaffe.sh

### ISSUE THREAD

**Issue by raghavgurbaxani** [jetsonhacks/installCaffeJTX2#4]
Hi, 

thank you for the excellent work. I encounter the following error. 

Would appreciate your help.

src/caffe/test/CMakeFiles/runtest.dir/build.make:57: recipe for target 'src/caffe/test/CMakeFiles/runtest' failed
make[3]: *** [src/caffe/test/CMakeFiles/runtest] Aborted (core dumped)
CMakeFiles/Makefile2:360: recipe for target 'src/caffe/test/CMakeFiles/runtest.dir/all' failed
make[2]: *** [src/caffe/test/CMakeFiles/runtest.dir/all] Error 2
CMakeFiles/Makefile2:367: recipe for target 'src/caffe/test/CMakeFiles/runtest.dir/rule' failed
make[1]: *** [src/caffe/test/CMakeFiles/runtest.dir/rule] Error 2
Makefile:253: recipe for target 'runtest' failed
make: *** [runtest] Error 2

**Comment by jetsonhacks** [comment]
All there is here is a listing that you have an error. Please provide:
The version of L4T that you are running.
The version of CUDA that is installed
Indicate whether cuDNN is installed.

Since there is no error message other than 'it failed', please provide the actual error encountered.

**Comment by raghavgurbaxani** [comment]
Hi 
the specs are ..

 NVIDIA Jetson TX2
 L4T 28.1.0 [ JetPack 3.1 ]
 Board: t186ref
 Ubuntu 16.04.4 LTS
 Kernel Version: 4.4.38-tegra
 CUDA 9.0.252

here is the full error 

[ 98%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_net.cpp.o
[100%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_hinge_loss_layer.cpp.o
[100%] Linking CXX executable ../../../test/test.testbin
[100%] Built target test.testbin
Scanning dependencies of target runtest
Cuda number of devices: 0
Current device id: 0
Current device name: 
Note: Randomizing tests' orders with a seed of 87586 .
[==========] Running 2199 tests from 285 test cases.
[----------] Global test environment set-up.
[----------] 7 tests from SyncedMemoryTest
[ RUN      ] SyncedMemoryTest.TestInitialization
[       OK ] SyncedMemoryTest.TestInitialization (0 ms)
[ RUN      ] SyncedMemoryTest.TestAllocationGPU
F0518 19:09:17.844614 14331 syncedmem.cpp:71] Check failed: error == cudaSuccess (35 vs. 0)  CUDA driver version is insufficient for CUDA runtime version
*** Check failure stack trace: ***
    @       0x7f99f65718  google::LogMessage::Fail()
    @       0x7f99f67614  google::LogMessage::SendToLog()
    @       0x7f99f65290  google::LogMessage::Flush()
    @       0x7f99f67eb4  google::LogMessageFatal::~LogMessageFatal()
    @       0x7f9a33a2f0  caffe::SyncedMemory::gpu_data()
    @           0xcdd188  caffe::SyncedMemoryTest_TestAllocationGPU_Test::TestBody()
    @           0xdbc3d4  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0xdb532c  testing::Test::Run()
    @           0xdb5468  testing::TestInfo::Run()
    @           0xdb5574  testing::TestCase::Run()
    @           0xdb6fd8  testing::internal::UnitTestImpl::RunAllTests()
    @           0xdb72ec  testing::UnitTest::Run()
    @           0x8d2af0  main
    @       0x7f94eaf8a0  __libc_start_main
src/caffe/test/CMakeFiles/runtest.dir/build.make:57: recipe for target 'src/caffe/test/CMakeFiles/runtest' failed
make[3]: *** [src/caffe/test/CMakeFiles/runtest] Aborted (core dumped)
CMakeFiles/Makefile2:360: recipe for target 'src/caffe/test/CMakeFiles/runtest.dir/all' failed
make[2]: *** [src/caffe/test/CMakeFiles/runtest.dir/all] Error 2
CMakeFiles/Makefile2:367: recipe for target 'src/caffe/test/CMakeFiles/runtest.dir/rule' failed
make[1]: *** [src/caffe/test/CMakeFiles/runtest.dir/rule] Error 2
Makefile:253: recipe for target 'runtest' failed
make: *** [runtest] Error 2

**Comment by jetsonhacks** [comment]
Your L4T version does not match the correct CUDA version. The CUDA version should be 8.0 for L4T 28.1. How did you install CUDA?

**Comment by raghavgurbaxani** [comment]
I updated the cuda version and it worked.  Thanks a lot :+1:
